In [15]:
## logistic regression for 2012
import os
os.chdir('c:/Users\\aknob\Desktop\Data')

import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn import *


#load dataset
silc = pd.read_csv('thesis_data_2012.csv')

silcSubSet = silc.dropna(axis=1, thresh = 4000) # drop columns that have > 4000 NaN
silcSubSet = silcSubSet.dropna(axis=0, thresh = 120) # drop rows that have >120   NaN

silcSubSet = silcSubSet.drop(['HB020', 'PB020', 'RB020', 'DB020', "PB220A", 'PL111'], axis = 1) # all values are NL, as it is dutch data, and thus not influenctal
## scores with 020 are country, pb220a is country of birth, PL111 is working sector categorized by letters

## imputate the NaN values that are left by adding the mean of that column 
silcSubSet = silcSubSet.fillna(silcSubSet.mean(), inplace=False)

## some categories (e.g. continuous) of variables are changed and now usable by sk learn
silcSubSet = silcSubSet.apply(LabelEncoder().fit_transform) 

# assign variables
y = silcSubSet[['PH010']]
x = silcSubSet.drop(y, axis = 1)

# split X and y into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1) ##80% used for training 20% for test

# Create an instance of Logistic Regression Classifier and fit the data.
param_grid = {'criterion':['gini', 'entropy']}
clf = GridSearchCV(DecisionTreeClassifier(class_weight = 'balanced'), param_grid, cv= 5)
clf.fit(x_train, y_train)
clf.predict(x_test)
y_pred = clf.predict(x_test)

# test score
score = clf.score(x_test, y_test)
print(score)

#predict probability
#print(lr.predict_proba(x_test))

from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))





C:\Users\aknob\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (1,223,253,303,506) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


[[27 46 38 18  8  4]
 [39 97 98 53 12  2]
 [35 89 77 39  8  2]
 [19 36 33 10  3  2]
 [ 4 13 10  5  1  1]
 [ 1  1  0  0  0  0]]
0.25511432009626955
Mean Absolute Error: 1.1961492178098676
Mean Squared Error: 2.4332129963898916
Root Mean Squared Error: 1.5598759554496286
              precision    recall  f1-score   support

           0       0.22      0.19      0.20       141
           1       0.34      0.32      0.33       301
           2       0.30      0.31      0.30       250
           3       0.08      0.10      0.09       103
           4       0.03      0.03      0.03        34
           5       0.00      0.00      0.00         2

    accuracy                           0.26       831
   macro avg       0.16      0.16      0.16       831
weighted avg       0.26      0.26      0.26       831

