In [2]:
## logistic regression for 2012
import os
os.chdir('c:/Users\\aknob\Desktop\Data')

import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn import *


#load dataset
silc = pd.read_csv('thesis_data_2012.csv')

silcSubSet = silc.dropna(axis=1, thresh = 4000) # drop columns that have > 4000 NaN
silcSubSet = silcSubSet.dropna(axis=0, thresh = 120) # drop rows that have >120   NaN

silcSubSet = silcSubSet.drop(['HB020', 'PB020', 'RB020', 'DB020', "PB220A", 'PL111'], axis = 1) # all values are NL, as it is dutch data, and thus not influenctal
## scores with 020 are country, pb220a is country of birth, PL111 is working sector categorized by letters

## imputate the NaN values that are left by adding the mean of that column 
silcSubSet = silcSubSet.fillna(silcSubSet.mean(), inplace=False)

## some categories (e.g. continuous) of variables are changed and now usable by sk learn
silcSubSet = silcSubSet.apply(LabelEncoder().fit_transform) 

# assign variables
y = silcSubSet[['PH010']]
x = silcSubSet.drop(y, axis = 1)

# split X and y into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1) ##80% used for training 20% for test

# Create an instance of Logistic Regression Classifier and fit the data.
#balancing classes for training

tuned_parameters = { 'C': [0.1, 0.5, 1 ,5 , 10, 50, 100]}
clf = GridSearchCV(LogisticRegression(solver = 'liblinear', class_weight = 'balanced'), tuned_parameters, cv=5, scoring = "accuracy")
clf.fit(x_train, y_train)
clf.predict(x_test)
y_pred = clf.predict(x_test)

#confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)


# test score 
print(score)

#predict probability

from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))





C:\Users\aknob\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\aknob\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\aknob\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\aknob\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\aknob\Anaconda3\

[[22 35 23 27 21 13]
 [46 83 68 37 42 25]
 [30 71 57 34 28 30]
 [15 24 17 13 19 15]
 [ 2  7  9  7  3  6]
 [ 0  0  0  0  2  0]]
0.21419975932611313
Mean Absolute Error: 1.5126353790613718
Mean Squared Error: 3.7918170878459687
Root Mean Squared Error: 1.9472588651347742
              precision    recall  f1-score   support

           0       0.19      0.16      0.17       141
           1       0.38      0.28      0.32       301
           2       0.33      0.23      0.27       250
           3       0.11      0.13      0.12       103
           4       0.03      0.09      0.04        34
           5       0.00      0.00      0.00         2

    accuracy                           0.21       831
   macro avg       0.17      0.15      0.15       831
weighted avg       0.28      0.21      0.24       831



C:\Users\aknob\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
